---
title: "Day 2 Tasks"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
## attach tidyverse and palmerpenguins
library(tidyverse)
library(palmerpenguins)
```

```{r}
# find the slope of f(x) = x^2 at x=3
eq1 <- function(x) {
  x^2
}
eq1

deriv_eq1 <- D(expr = expression(x^2), name = "x")
deriv_eq1

deriv_eq1_fun <- function(x) {
  2 * x 
}

deriv_eq1_fun(3)
```

```{r}
# Find the slope of f(a) = 2(3a+2)^4 - 5 at a = 1.2

eq2 <- function(a) {
  2 * (3*a+2)^4 - 5
}

deriv_eq2 <- D(expr = expression(2 * (3 * a +2)^4 - 5), name = "a")

deriv_eq2_fun <- function(a) {
  2 * (4 * (3 * (3 * a + 2)^3))
}

deriv_eq2_fun(1.2)
```


```{r}
# find penguins data from palmerpenguins library

penguins_data <- penguins

ggplot(data = penguins_data, aes(x = bill_depth_mm, y = bill_length_mm, colour = species)) +
         geom_point(na.rm = TRUE) + xlab("Bill Depth in mm") +
  ylab("Bill Length in mm") + ggtitle("Bill Depth vs. Bill Length in mm") 

```

```{r}
ggplot(penguins_data, aes(x = species, y = flipper_length_mm, colour = species)) +
  geom_jitter() + 
  xlab("Species") +
  ylab("Flipper Length in mm") +
  ggtitle("Flipper length by Species of Penguins")
  
```

